-- les données pour la courbe des ages de tout le monde
select age, coalesce(nb, 0) nb, coalesce(lol, 0) "pour cent", sum(coalesce(lol, 0)) over (order by age) "somme des pourcent" from generate_series(1, 99) s(age) left outer join (select date_part('year', age(birthdate)) age, count(*) nb, (count(*)::numeric * 100::numeric) / (select count(*) from p where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99)::numeric lol from p where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 group by date_part('year', age(birthdate))) t using (age) order by age

-- les données pour la courbe des ages des actifs en 2020
select age, coalesce(nb, 0) nb, coalesce(lol, 0) "pour cent", sum(coalesce(lol, 0)) over (order by age) "somme des pourcent" from generate_series(1, 99) s(age) left outer join (select date_part('year', age(birthdate)) age, count(*) nb, (count(*)::numeric * 100::numeric) / (select count(*) from p where lastpostdate >= '2020-01-01' and date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99)::numeric lol from p where lastpostdate >= '2020-01-01' and date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 group by date_part('year', age(birthdate))) t using (age) order by age

-- pourcentage d'ages valides de tout le monde
-- 36.4450175579599194
select count(*) nb, count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99) "nb valides", (count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99)::numeric * 100::numeric) / count(*)::numeric "pourcentage de valides" from p

-- pourcentage d'ages valides des actifs en 2020
-- 53.6117541456040062
select count(*) nb, count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99) "nb valides", (count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99)::numeric * 100::numeric) / count(*)::numeric "pourcentage de valides" from p where lastpostdate >= '2020-01-01'

-- age moyen de tout le monde
-- 38.382509415484
select avg(date_part('year', age(birthdate))) "age moyen" from p where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99

-- age moyen des actifs en 2020
-- 36.5272294677476
select avg(date_part('year', age(birthdate))) "age moyen" from p where lastpostdate >= '2020-01-01' and date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99

-- age médian de tout le monde
-- 36
select percentile_cont(0.5) within group (order by date_part('year', age(birthdate)) asc) "age médian" from p where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99

-- age médian des actifs en 2020
-- 36
select percentile_cont(0.5) within group (order by date_part('year', age(birthdate)) asc) "age médian" from p where lastpostdate >= '2020-01-01' and date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99

-- les classes d'ages réels par age hfr de tout le monde
select date_part('year', age(case when creationdate is null or creationdate < '2000-01-01' then '2000-01-01' else creationdate end)) age_hfr, count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 0) "0+", count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 1) "10+", count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 2) "20+", count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 3) "30+", count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 4) "40+", count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 5) "50+", count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 6) "60+", count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 7) "70+", count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 8) "80+", count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 9) "90+", count(*) tous from p where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 group by age_hfr order by age_hfr

-- les classes d'ages réels par age hfr de tout le monde avec invalides
select date_part('year', age(case when creationdate is null or creationdate < '2000-01-01' then '2000-01-01' else creationdate end)) age_hfr, count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 0) "0+", count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 1) "10+", count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 2) "20+", count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 3) "30+", count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 4) "40+", count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 5) "50+", count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 6) "60+", count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 7) "70+", count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 8) "80+", count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 9) "90+", count(*) filter (where date_part('year', age(birthdate)) < 1 or date_part('year', age(birthdate)) > 99 or birthdate is null) "invalides", count(*) tous from p group by age_hfr order by age_hfr

-- les classes d'ages réels normalisées par age hfr de tout le monde
select date_part('year', age(case when creationdate is null or creationdate < '2000-01-01' then '2000-01-01' else creationdate end)) age_hfr, ((count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 0))::numeric * 100::numeric) / count(*)::numeric "0+", ((count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 1))::numeric * 100::numeric) / count(*)::numeric "10+", ((count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 2))::numeric * 100::numeric) / count(*)::numeric "20+", ((count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 3))::numeric * 100::numeric) / count(*)::numeric "30+", ((count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 4))::numeric * 100::numeric) / count(*)::numeric "40+",(( count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 5))::numeric * 100::numeric) / count(*)::numeric "50+", ((count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 6))::numeric * 100::numeric) / count(*)::numeric "60+", ((count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 7))::numeric * 100::numeric) / count(*)::numeric "70+", ((count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 8))::numeric * 100::numeric) / count(*)::numeric "80+", ((count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 9))::numeric * 100::numeric) / count(*)::numeric "90+", count(*) tous from p where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 group by age_hfr order by age_hfr

-- les classes d'ages réels normalisées par age hfr de tout le monde avec invalides
select date_part('year', age(case when creationdate is null or creationdate < '2000-01-01' then '2000-01-01' else creationdate end)) age_hfr, ((count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 0))::numeric * 100::numeric) / count(*)::numeric "0+", ((count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 1))::numeric * 100::numeric) / count(*)::numeric "10+", ((count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 2))::numeric * 100::numeric) / count(*)::numeric "20+", ((count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 3))::numeric * 100::numeric) / count(*)::numeric "30+", ((count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 4))::numeric * 100::numeric) / count(*)::numeric "40+",(( count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 5))::numeric * 100::numeric) / count(*)::numeric "50+", ((count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 6))::numeric * 100::numeric) / count(*)::numeric "60+", ((count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 7))::numeric * 100::numeric) / count(*)::numeric "70+", ((count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 8))::numeric * 100::numeric) / count(*)::numeric "80+", ((count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 9))::numeric * 100::numeric) / count(*)::numeric "90+", ((count(*) filter (where date_part('year', age(birthdate)) < 1 or date_part('year', age(birthdate)) > 99 or birthdate is null))::numeric * 100::numeric) / count(*)::numeric "invalides", count(*) tous from p group by age_hfr order by age_hfr

-- les classes d'ages réels par age hfr des actifs en 2020
select date_part('year', age(case when creationdate is null or creationdate < '2000-01-01' then '2000-01-01' else creationdate end)) age_hfr, count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 0) "0+", count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 1) "10+", count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 2) "20+", count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 3) "30+", count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 4) "40+", count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 5) "50+", count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 6) "60+", count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 7) "70+", count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 8) "80+", count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 9) "90+", count(*) tous from p where lastpostdate >= '2020-01-01' and date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 group by age_hfr order by age_hfr

-- les classes d'ages réels par age hfr des actifs en 2020 avec invalides
select date_part('year', age(case when creationdate is null or creationdate < '2000-01-01' then '2000-01-01' else creationdate end)) age_hfr, count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 0) "0+", count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 1) "10+", count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 2) "20+", count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 3) "30+", count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 4) "40+", count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 5) "50+", count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 6) "60+", count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 7) "70+", count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 8) "80+", count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 9) "90+", count(*) filter (where date_part('year', age(birthdate)) < 1 or date_part('year', age(birthdate)) > 99 or birthdate is null) "invalides", count(*) tous from p where lastpostdate >= '2020-01-01' group by age_hfr order by age_hfr

-- les classes d'ages réels normalisées par age hfr des actifs en 2020
select date_part('year', age(case when creationdate is null or creationdate < '2000-01-01' then '2000-01-01' else creationdate end)) age_hfr, ((count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 0))::numeric * 100::numeric) / count(*)::numeric "0+", ((count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 1))::numeric * 100::numeric) / count(*)::numeric "10+", ((count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 2))::numeric * 100::numeric) / count(*)::numeric "20+", ((count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 3))::numeric * 100::numeric) / count(*)::numeric "30+", ((count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 4))::numeric * 100::numeric) / count(*)::numeric "40+",(( count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 5))::numeric * 100::numeric) / count(*)::numeric "50+", ((count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 6))::numeric * 100::numeric) / count(*)::numeric "60+", ((count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 7))::numeric * 100::numeric) / count(*)::numeric "70+", ((count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 8))::numeric * 100::numeric) / count(*)::numeric "80+", ((count(*) filter (where floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 9))::numeric * 100::numeric) / count(*)::numeric "90+", count(*) tous from p where lastpostdate >= '2020-01-01' and date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 group by age_hfr order by age_hfr

-- les classes d'ages réels normalisées par age hfr des actifs en 2020 avec invalides
select date_part('year', age(case when creationdate is null or creationdate < '2000-01-01' then '2000-01-01' else creationdate end)) age_hfr, ((count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 0))::numeric * 100::numeric) / count(*)::numeric "0+", ((count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 1))::numeric * 100::numeric) / count(*)::numeric "10+", ((count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 2))::numeric * 100::numeric) / count(*)::numeric "20+", ((count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 3))::numeric * 100::numeric) / count(*)::numeric "30+", ((count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 4))::numeric * 100::numeric) / count(*)::numeric "40+",(( count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 5))::numeric * 100::numeric) / count(*)::numeric "50+", ((count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 6))::numeric * 100::numeric) / count(*)::numeric "60+", ((count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 7))::numeric * 100::numeric) / count(*)::numeric "70+", ((count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 8))::numeric * 100::numeric) / count(*)::numeric "80+", ((count(*) filter (where date_part('year', age(birthdate)) >= 1 and date_part('year', age(birthdate)) <= 99 and floor(date_part('year', age(birthdate))::numeric / 10::numeric) = 9))::numeric * 100::numeric) / count(*)::numeric "90+", ((count(*) filter (where date_part('year', age(birthdate)) < 1 or date_part('year', age(birthdate)) > 99 or birthdate is null))::numeric * 100::numeric) / count(*)::numeric "invalides", count(*) tous from p where lastpostdate >= '2020-01-01' group by age_hfr order by age_hfr

